//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;

	public partial class ExecutionTrace
	{
		#region [ Initialize Method ]

		/// <summary>
		/// Initialize the object when the instance is created.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Enter your custom code here...
		}

		#endregion

		#region [ Calculated Properties ]

		/// <summary>
		/// Gets the Average Duration of the execution time.
		/// </summary>
		public long AvgDuration
		{
			get
			{
				return (this.Counter != 0) ? this.TotalDuration / this.Counter : 0;
			}
		}

		#endregion

		#region [ Validation Methods ]

		// Enter the 'partial' keywork and press 'SPACE' key to get the partial methods that can be define...

		#endregion
	}

	public static class ExecutionTraceExtensions
	{
		// Enter your custom extensions methods here...
	}
}