//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.Data;
	using System.Diagnostics;
	using System.Linq;
	using System.Runtime.Serialization;
	using System.Xml.Serialization;

	using VahapYigit.Test.Core;

	/// <summary>
	/// Entity mapped to ProcessLog DB table.
	/// </summary>
	[Serializable]
	[DataContract(Namespace = Globals.Namespace, IsReference = true)]
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
	public partial class ProcessLog : EntityBase, IProcessLog
	{
		/// <summary>
		/// Gets the name of the entity.
		/// </summary>
		public static readonly string EntityName = "ProcessLog";

		#region [ Constructor ]

		/// <summary>
		/// Default constructor.
		/// </summary>
		public ProcessLog()
			: base()
		{
			this.Initialize();
		}

		#endregion

		#region [ Events ]

		#endregion

		#region [ Column Names ]

		/// <summary>
		/// Contains the entity column names.
		/// </summary>
		public static partial class ColumnNames
		{
			/// <summary>
			/// Name of the Id column ("ProcessLog_Id").
			/// </summary>
			public static readonly string Id = "ProcessLog_Id";

			/// <summary>
			/// Name of the Date column ("ProcessLog_Date").
			/// </summary>
			public static readonly string Date = "ProcessLog_Date";

			/// <summary>
			/// Name of the ProcedureName column ("ProcessLog_ProcedureName").
			/// </summary>
			public static readonly string ProcedureName = "ProcessLog_ProcedureName";

			/// <summary>
			/// Name of the Data column ("ProcessLog_Data").
			/// </summary>
			public static readonly string Data = "ProcessLog_Data";

		}

		#endregion

		#region [ Property Names ]

		/// <summary>
		/// Contains the entity property names.
		/// </summary>
		public static partial class PropertyNames
		{
			/// <summary>
			/// Name of the Id property ("Id").
			/// </summary>
			public static readonly string Id = "Id";

			/// <summary>
			/// Name of the Date property ("Date").
			/// </summary>
			public static readonly string Date = "Date";

			/// <summary>
			/// Name of the ProcedureName property ("ProcedureName").
			/// </summary>
			public static readonly string ProcedureName = "ProcedureName";

			/// <summary>
			/// Name of the Data property ("Data").
			/// </summary>
			public static readonly string Data = "Data";

		}

		#endregion

		#region [ Properties ]

		#region [ Date ]

		private DateTime _Date;

		/// <summary>
		/// Gets or sets the Date value (MANDATORY). 
		/// </summary>
		[DebuggerHidden]
		[Required]
		[DataMember()]
		public virtual DateTime Date
		{
			get { return _Date; }
			set
			{
				if (value != _Date)
				{
					_Date = value;

					if (!_deserializing)
					{
						base.UpdateState();
					}

					this.NotifyPropertyChanged();

					if (!_deserializing)
					{
						this.ValidateDate();
					}
				}
			}
		}

		/// <summary>
		/// Method called on Date value validation.
		/// </summary>
		/// 
		/// <param name="error">
		/// Indicates whether the Date value is valid (format, value, etc).
		/// </param>
		partial void OnDateValidation(ref TranslationEnum? error);

		private bool ValidateDate()
		{
			bool isValid = false;

			do
			{
				if (this.Date == DateTime.MinValue)
				{
					base.AddValidationError("Date", TranslationEnum.ModelProcessLogDateIsRequired);
					break;
				}

				TranslationEnum? error = null;

				this.OnDateValidation(ref error);
				if (error != null)
				{
					base.AddValidationError("Date", error.Value);
					break;
				}

				base.RemoveValidationErrors("Date");
				isValid = true;
			}
			while (false);

			return isValid;
		}

		#endregion

		#region [ ProcedureName ]

		private string _ProcedureName;

		/// <summary>
		/// Gets or sets the ProcedureName value (MANDATORY). 
		/// </summary>
		[DebuggerHidden]
		[Required]
		[DataMember()]
		public virtual string ProcedureName
		{
			get { return _ProcedureName; }
			set
			{
				if (value != _ProcedureName)
				{
					_ProcedureName = value;

					if (!_deserializing)
					{
						base.UpdateState();
					}

					this.NotifyPropertyChanged();

					if (!_deserializing)
					{
						this.ValidateProcedureName();
					}
				}
			}
		}

		/// <summary>
		/// Method called on ProcedureName value validation.
		/// </summary>
		/// 
		/// <param name="error">
		/// Indicates whether the ProcedureName value is valid (format, value, etc).
		/// </param>
		partial void OnProcedureNameValidation(ref TranslationEnum? error);

		private bool ValidateProcedureName()
		{
			bool isValid = false;

			do
			{
				if (this.ProcedureName == null)
				{
					base.AddValidationError("ProcedureName", TranslationEnum.ModelProcessLogProcedureNameIsRequired);
					break;
				}

				TranslationEnum? error = null;

				this.OnProcedureNameValidation(ref error);
				if (error != null)
				{
					base.AddValidationError("ProcedureName", error.Value);
					break;
				}

				base.RemoveValidationErrors("ProcedureName");
				isValid = true;
			}
			while (false);

			return isValid;
		}

		#endregion

		#region [ Data ]

		private string _Data;

		/// <summary>
		/// Gets or sets the Data value (OPTIONAL). 
		/// </summary>
		[DebuggerHidden]
		[DataMember()]
		public virtual string Data
		{
			get { return _Data; }
			set
			{
				if (value != _Data)
				{
					_Data = value;

					if (!_deserializing)
					{
						base.UpdateState();
					}

					this.NotifyPropertyChanged();

					if (!_deserializing)
					{
						this.ValidateData();
					}
				}
			}
		}

		/// <summary>
		/// Method called on Data value validation.
		/// </summary>
		/// 
		/// <param name="error">
		/// Indicates whether the Data value is valid (format, value, etc).
		/// </param>
		partial void OnDataValidation(ref TranslationEnum? error);

		private bool ValidateData()
		{
			bool isValid = false;

			do
			{
				TranslationEnum? error = null;

				this.OnDataValidation(ref error);
				if (error != null)
				{
					base.AddValidationError("Data", error.Value);
					break;
				}

				base.RemoveValidationErrors("Data");
				isValid = true;
			}
			while (false);

			return isValid;
		}

		#endregion

		#endregion

		#region [ References ]

		#endregion

		#region [ EntityBase Implementation ]

		/// <summary>
		/// Gets the entity properties validity.
		/// </summary>
		/// 
		/// <param name="errors">
		/// Translation errors list (each item represents a translation key of an error).
		/// </param>
		/// 
		/// <returns>
		/// True if all the entity properties are correct; otherwise, false.
		/// </returns>
		public override bool IsValid(out IList<TranslationEnum> errors)
		{
			IList<TranslationEnum> errs = new List<TranslationEnum>();

			if (!this.ValidateDate())
			{
				var iterator = ((INotifyDataErrorInfo)this).GetErrors("Date");
				iterator.ForEach(error => errs.Add((TranslationEnum)error));
			}

			if (!this.ValidateProcedureName())
			{
				var iterator = ((INotifyDataErrorInfo)this).GetErrors("ProcedureName");
				iterator.ForEach(error => errs.Add((TranslationEnum)error));
			}

			if (!this.ValidateData())
			{
				var iterator = ((INotifyDataErrorInfo)this).GetErrors("Data");
				iterator.ForEach(error => errs.Add((TranslationEnum)error));
			}

			errors = errs;

			return errors.Count == 0;
		}
		
		/// <summary>
		/// Fill the entity properties using a source.
		/// </summary>
		/// 
		/// <param name="source">
		/// Source.
		public override void Map(EntityBase source)
		{
			if (source == null)
			{
				ThrowException.ThrowArgumentNullException("source");
			}

			if (!(source is ProcessLog))
			{
				ThrowException.ThrowArgumentException("The 'source' argument is not a 'ProcessLog' instance");
			}

			this.Date = ((ProcessLog)source).Date;
			this.ProcedureName = ((ProcessLog)source).ProcedureName;
			this.Data = ((ProcessLog)source).Data;

			this.Id = source.Id;
			this.State = source.State;
		}

		/// <summary>
		/// Fills the entity properties using a IDataReader object.
		/// </summary>
		/// 
		/// <param name="source">
		/// IDataReader object.
		/// </param>
		/// 
		/// <param name="userContext">
		/// User context (use base.UserContext).
		/// </param>
		/// 
		/// <param name="columnPrefix">
		/// Column prefix (optional).
		/// </param>
		public override void Map(IDataReader source, IUserContext userContext, string columnPrefix = null)
		{
			if (columnPrefix == null)
			{
				columnPrefix = string.Concat(EntityName, "_");
			}

			this.Id = TypeHelper.To<long>(source[string.Format("{0}Id", columnPrefix)]);
			this.Date = TypeHelper.To<DateTime>(source[string.Format("{0}Date", columnPrefix)]);
			this.ProcedureName = TypeHelper.To<string>(source[string.Format("{0}ProcedureName", columnPrefix)]);
			this.Data = TypeHelper.To<string>(source[string.Format("{0}Data", columnPrefix)]);

			this.State = EntityState.None;
		}

		/// <summary>
		/// Fill the entity properties using a DataRow object.
		/// </summary>
		/// 
		/// <param name="source">
		/// DataRow object.
		/// </param>
		/// 
		/// <param name="userContext">
		/// User context (use base.UserContext).
		/// </param>
		/// 
		/// <param name="columnPrefix">
		/// Column prefix (optional).
		/// </param>
		public override void Map(DataRow source, IUserContext userContext, string columnPrefix = null)
		{
			if (columnPrefix == null)
			{
				columnPrefix = string.Concat(EntityName, "_");
			}

			this.Id = TypeHelper.To<long>(source[string.Format("{0}Id", columnPrefix)]);
			this.Date = TypeHelper.To<DateTime>(source[string.Format("{0}Date", columnPrefix)]);
			this.ProcedureName = TypeHelper.To<string>(source[string.Format("{0}ProcedureName", columnPrefix)]);
			this.Data = TypeHelper.To<string>(source[string.Format("{0}Data", columnPrefix)]);

			this.State = EntityState.None;
		}
		
		/// <summary>
		/// Fills the entity properties and all its dependencies using a IDataReader object.
		/// </summary>
		/// 
		/// <param name="source">
		/// IDataReader object.
		/// </param>
		///
		/// <param name="userContext">
		/// User context (optional).
		/// </param>
		public override void DeepMap(IDataReader source, IUserContext userContext = null)
		{
			this.Map(source, userContext);

			this.State = EntityState.None;
		}
		
		/// <summary>
		/// Fill the entity properties and all its dependencies using a DataRow object.
		/// </summary>
		/// 
		/// <param name="source">
		/// DataRow object.
		/// </param>
		///
		/// <param name="userContext">
		/// User context (optional).
		/// </param>
		public override void DeepMap(DataRow source, IUserContext userContext = null)
		{
			this.Map(source, userContext);

			this.State = EntityState.None;
		}

		#endregion
	}
}