//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Business
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Net.Security;
	using System.ServiceModel;

	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;
	using VahapYigit.Test.Models;

	/// <summary>
	/// This class contains Common business methods.
	/// </summary>
	[BusinessClass]
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	public class CommonBusiness : BusinessBase
	{
		#region [ Custom public methods ]

		[BusinessMethod]
		public IList<GlobalSearchResultItem> GlobalSearch(IUserContext userContext, string keyword, ref PagingOptions paging, IEnumerable<string> restrictionTableNames = null)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new CommonCrud(userContext))
			{
				return db.GlobalSearch(keyword, ref paging, restrictionTableNames);
			}
		}

		[BusinessMethod]
		public IList<TableSizeModel> GetTableSizes(IUserContext userContext)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new CommonCrud(userContext))
			{
				return db.GetTableSizes();
			}
		}

		#endregion
	}
}