//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Core
{
	using System.Collections.Generic;

	public static partial class Cultures
	{
		/// <summary>
		/// "EN".
		/// </summary>
		public static readonly string EN = "EN";

		/// <summary>
		/// Gets the list of the supported cultures.
		/// </summary>
		public static IList<string> CultureList
		{
			get
			{
				return new List<string>()
				{
					Cultures.EN
				};
			}
		}
	}
}