-- ------------------------------------------------------------------------------ 
-- <auto-generated> 
-- This code was generated by LayerCake Generator v3.7.1.
-- http://www.layercake-generator.net
-- 
-- Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
-- the code is regenerated. 
-- </auto-generated> 
-- ------------------------------------------------------------------------------

-- DO NOT ADD THIS FILE TO THE DATABASE PROJECT!

-- NOTE: this script is executed on the target database when generated.

INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelAppSettingsKeyIsRequired', 'EN_ModelAppSettingsKeyIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelAppSettingsKeyIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelAppSettingsKeyBadValueOrFormat', 'EN_ModelAppSettingsKeyBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelAppSettingsKeyBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelAppSettingsValueIsRequired', 'EN_ModelAppSettingsValueIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelAppSettingsValueIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelAppSettingsValueBadValueOrFormat', 'EN_ModelAppSettingsValueBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelAppSettingsValueBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelAppSettingsDescriptionBadValueOrFormat', 'EN_ModelAppSettingsDescriptionBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelAppSettingsDescriptionBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceModuleIsRequired', 'EN_ModelExecutionTraceModuleIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceModuleIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceModuleBadValueOrFormat', 'EN_ModelExecutionTraceModuleBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceModuleBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceClassNameIsRequired', 'EN_ModelExecutionTraceClassNameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceClassNameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceClassNameBadValueOrFormat', 'EN_ModelExecutionTraceClassNameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceClassNameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMethodNameIsRequired', 'EN_ModelExecutionTraceMethodNameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMethodNameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMethodNameBadValueOrFormat', 'EN_ModelExecutionTraceMethodNameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMethodNameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceTagBadValueOrFormat', 'EN_ModelExecutionTraceTagBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceTagBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMinDurationIsRequired', 'EN_ModelExecutionTraceMinDurationIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMinDurationIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMinDurationBadValueOrFormat', 'EN_ModelExecutionTraceMinDurationBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMinDurationBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMaxDurationIsRequired', 'EN_ModelExecutionTraceMaxDurationIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMaxDurationIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceMaxDurationBadValueOrFormat', 'EN_ModelExecutionTraceMaxDurationBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceMaxDurationBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceTotalDurationIsRequired', 'EN_ModelExecutionTraceTotalDurationIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceTotalDurationIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceTotalDurationBadValueOrFormat', 'EN_ModelExecutionTraceTotalDurationBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceTotalDurationBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceCounterIsRequired', 'EN_ModelExecutionTraceCounterIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceCounterIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceCounterBadValueOrFormat', 'EN_ModelExecutionTraceCounterBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceCounterBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceLastCallIsRequired', 'EN_ModelExecutionTraceLastCallIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceLastCallIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelExecutionTraceLastCallBadValueOrFormat', 'EN_ModelExecutionTraceLastCallBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelExecutionTraceLastCallBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogDateIsRequired', 'EN_ModelProcessErrorLogDateIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogDateIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogDateBadValueOrFormat', 'EN_ModelProcessErrorLogDateBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogDateBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogProcedureNameIsRequired', 'EN_ModelProcessErrorLogProcedureNameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogProcedureNameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogProcedureNameBadValueOrFormat', 'EN_ModelProcessErrorLogProcedureNameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogProcedureNameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogErrorMessageBadValueOrFormat', 'EN_ModelProcessErrorLogErrorMessageBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogErrorMessageBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogErrorSeverityBadValueOrFormat', 'EN_ModelProcessErrorLogErrorSeverityBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogErrorSeverityBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogErrorStateBadValueOrFormat', 'EN_ModelProcessErrorLogErrorStateBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogErrorStateBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessErrorLogDataBadValueOrFormat', 'EN_ModelProcessErrorLogDataBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessErrorLogDataBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessLogDateIsRequired', 'EN_ModelProcessLogDateIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessLogDateIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessLogDateBadValueOrFormat', 'EN_ModelProcessLogDateBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessLogDateBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessLogProcedureNameIsRequired', 'EN_ModelProcessLogProcedureNameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessLogProcedureNameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessLogProcedureNameBadValueOrFormat', 'EN_ModelProcessLogProcedureNameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessLogProcedureNameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelProcessLogDataBadValueOrFormat', 'EN_ModelProcessLogDataBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelProcessLogDataBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelRoleCodeRefIsRequired', 'EN_ModelRoleCodeRefIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelRoleCodeRefIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelRoleCodeRefBadValueOrFormat', 'EN_ModelRoleCodeRefBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelRoleCodeRefBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelRoleNameIsRequired', 'EN_ModelRoleNameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelRoleNameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelRoleNameBadValueOrFormat', 'EN_ModelRoleNameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelRoleNameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelTranslationKeyIsRequired', 'EN_ModelTranslationKeyIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelTranslationKeyIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelTranslationKeyBadValueOrFormat', 'EN_ModelTranslationKeyBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelTranslationKeyBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelTranslationValueIsRequired', 'EN_ModelTranslationValueIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelTranslationValueIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelTranslationValueBadValueOrFormat', 'EN_ModelTranslationValueBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelTranslationValueBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserUsernameIsRequired', 'EN_ModelUserUsernameIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserUsernameIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserUsernameBadValueOrFormat', 'EN_ModelUserUsernameBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserUsernameBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordIsRequired', 'EN_ModelUserPasswordIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordBadValueOrFormat', 'EN_ModelUserPasswordBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserEmailIsRequired', 'EN_ModelUserEmailIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserEmailIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserEmailBadValueOrFormat', 'EN_ModelUserEmailBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserEmailBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordQuestionIsRequired', 'EN_ModelUserPasswordQuestionIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordQuestionIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordQuestionBadValueOrFormat', 'EN_ModelUserPasswordQuestionBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordQuestionBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordResponseIsRequired', 'EN_ModelUserPasswordResponseIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordResponseIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserPasswordResponseBadValueOrFormat', 'EN_ModelUserPasswordResponseBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserPasswordResponseBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRegistrationDateIsRequired', 'EN_ModelUserRegistrationDateIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRegistrationDateIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRegistrationDateBadValueOrFormat', 'EN_ModelUserRegistrationDateBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRegistrationDateBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserLastConnectionDateBadValueOrFormat', 'EN_ModelUserLastConnectionDateBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserLastConnectionDateBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserCultureIsRequired', 'EN_ModelUserCultureIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserCultureIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserCultureBadValueOrFormat', 'EN_ModelUserCultureBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserCultureBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRoleIdUserIsRequired', 'EN_ModelUserRoleIdUserIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRoleIdUserIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRoleIdUserBadValueOrFormat', 'EN_ModelUserRoleIdUserBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRoleIdUserBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRoleIdRoleIsRequired', 'EN_ModelUserRoleIdRoleIsRequired' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRoleIdRoleIsRequired'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'ModelUserRoleIdRoleBadValueOrFormat', 'EN_ModelUserRoleIdRoleBadValueOrFormat' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'ModelUserRoleIdRoleBadValueOrFormat'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudAppSettingsKeyUniqueConstraint', 'EN_CrudAppSettingsKeyUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudAppSettingsKeyUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudRoleCodeRefUniqueConstraint', 'EN_CrudRoleCodeRefUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudRoleCodeRefUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudRoleNameUniqueConstraint', 'EN_CrudRoleNameUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudRoleNameUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudTranslationKeyUniqueConstraint', 'EN_CrudTranslationKeyUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudTranslationKeyUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudUserEmailUniqueConstraint', 'EN_CrudUserEmailUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudUserEmailUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudUserUsernameUniqueConstraint', 'EN_CrudUserUsernameUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudUserUsernameUniqueConstraint'));
GO
INSERT INTO [Translation] ([Translation_Key], [Translation_Value_EN]) SELECT 'CrudUserRoleIdUser_IdRoleUniqueConstraint', 'EN_CrudUserRoleIdUser_IdRoleUniqueConstraint' WHERE NOT(EXISTS(SELECT * FROM [Translation] WHERE [Translation_Key] = 'CrudUserRoleIdUser_IdRoleUniqueConstraint'));
GO
