//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Contracts
{
	using System;
	using System.Net.Security;
	using System.ServiceModel;
	using System.ServiceModel.Web;
	using System.Threading.Tasks;
	using System.Xml;

	/// <summary>
	/// AppSettingsService Contract.
	/// </summary>
	[ServiceContract(Namespace = VahapYigit.Test.Core.Globals.Namespace)]
	[ServiceKnownType(typeof(VahapYigit.Test.Core.ClientContext))]
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public partial interface IAppSettingsService : IService
	{
		#region [ IAppSettingsService ]
		
		/// <summary>
		/// Refreshs the entity instance from the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="appSettings">
		/// Entity to refresh (must be in database).
		/// </param>
		[OperationContract(Name = "GeneratedRefresh")]
		void Refresh(VahapYigit.Test.Core.IUserContext userContext, ref VahapYigit.Test.Models.AppSettings entity);
		
		/// <summary>
		/// Gets an entity given its unique ID.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="id">
		/// Unique ID.
		/// </param>
		/// 
		/// <returns>
		/// The entity.
		/// </returns>
		[OperationContract(Name = "GeneratedGetById")]
		VahapYigit.Test.Models.AppSettings GetById(VahapYigit.Test.Core.IUserContext userContext, long id);

		/// <summary>
		/// Gets entities with search options.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional options, filters, orderby, paging, etc..
		/// </param>
		/// 
		/// <returns>
		/// A collection of entities.
		/// </returns>
		[OperationContract(Name = "GeneratedSearch")]
		TCollection<VahapYigit.Test.Models.AppSettings> Search(VahapYigit.Test.Core.IUserContext userContext, ref VahapYigit.Test.Core.SearchOptions options);
		
		/// <summary>
		/// Gets the number of records that verify the search options.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional search options. If not defined all records are counted.
		/// </param>
		/// 
		/// <returns>
		/// The number of records.
		/// </returns>
		[OperationContract(Name = "GeneratedCount")]
		int Count(VahapYigit.Test.Core.IUserContext userContext, VahapYigit.Test.Core.SearchOptions options = null);
		
		/// <summary>
		/// Indicates whether the search returns at least 1 entity.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional options, filters, orderby, paging, etc.
		/// </param>
		/// 
		/// <returns>
		/// True if the search returns at least 1 entity; otherwise, false.
		/// </returns>
		[OperationContract(Name = "GeneratedHasResult")]
		bool HasResult(VahapYigit.Test.Core.IUserContext userContext, VahapYigit.Test.Core.SearchOptions options = null);
		
		/// <summary>
		/// Saves (or updates) the entity in the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		///
		/// <param name="entity">
		/// Entity to save or update.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional options.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		[OperationContract(Name = "GeneratedSave")]
		int Save(VahapYigit.Test.Core.IUserContext userContext, ref VahapYigit.Test.Models.AppSettings entity, VahapYigit.Test.Core.SaveOptions options = null);
		
		/// <summary>
		/// Deletes the entity from the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="entity">
		/// Entity to delete.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		[OperationContract(Name = "GeneratedDelete")]
		int Delete(VahapYigit.Test.Core.IUserContext userContext,VahapYigit.Test.Models.AppSettings entity);
		
		/// <summary>
		/// Deletes the entity given its unique ID.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="id">
		/// Unique ID.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		[OperationContract(Name = "GeneratedDeleteById")]
		int Delete(VahapYigit.Test.Core.IUserContext userContext, long id);

		#endregion

		#region [ IAppSettingsService Business ]
		#pragma warning disable 1591 // Disable 'missing XML comment for publicly visible type or member' warnings

		[OperationContract(Name = "GetByKey")]
		VahapYigit.Test.Models.AppSettings GetByKey(VahapYigit.Test.Core.IUserContext userContext, string key);
		
		[OperationContract(Name = "GetStringValue")]
		string GetStringValue(VahapYigit.Test.Core.IUserContext userContext, string key, string defaultValue = null);
		
		[OperationContract(Name = "GetBoolValue")]
		bool GetBoolValue(VahapYigit.Test.Core.IUserContext userContext, string key, bool defaultValue = false);
		
		[OperationContract(Name = "GetShortValue")]
		short GetShortValue(VahapYigit.Test.Core.IUserContext userContext, string key, short defaultValue = 0);
		
		[OperationContract(Name = "GetIntValue")]
		int GetIntValue(VahapYigit.Test.Core.IUserContext userContext, string key, int defaultValue = 0);
		
		[OperationContract(Name = "GetLongValue")]
		long GetLongValue(VahapYigit.Test.Core.IUserContext userContext, string key, long defaultValue = 0);
		
		#pragma warning restore 1591
		#endregion
	}
}