//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//-----------------------------------------------------------------------------

namespace VahapYigit.Test.Services
{
	using System;
	using System.ServiceModel;
	using System.ServiceModel.Activation;
	using System.Threading.Tasks;
	using System.Transactions;
	using System.Xml;
	
	using VahapYigit.Test.Business;
	using VahapYigit.Test.Contracts;
	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;

	/// <summary>
	/// CommonService Service.
	/// </summary>
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	[AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
	public partial class CommonService : ICommonService
	{
		#region [ IService Implementation ]
		
		bool IService.WakeUp(IUserContext userContext)
		{
			return true;
		}

		async Task<bool> IService.WakeUpAsync(IUserContext userContext)
		{
			return await Task.Factory.StartNew(() => true);
		}

		#endregion

		#region [ ICommonService Business Implementation ]
		#pragma warning disable 1591 // Disable 'missing XML comment for publicly visible type or member' warnings

		public System.Collections.Generic.IList<VahapYigit.Test.Models.GlobalSearchResultItem> GlobalSearch(VahapYigit.Test.Core.IUserContext userContext, string keyword, ref System.PagingOptions paging, System.Collections.Generic.IEnumerable<string> restrictionTableNames = null)
		{
			using (var et = new ExecutionTracerService())
			{
				var business = new CommonBusiness();
				return business.GlobalSearch(userContext, keyword, ref paging, restrictionTableNames);
			}
		}

		public System.Collections.Generic.IList<VahapYigit.Test.Models.TableSizeModel> GetTableSizes(VahapYigit.Test.Core.IUserContext userContext)
		{
			using (var et = new ExecutionTracerService())
			{
				var business = new CommonBusiness();
				return business.GetTableSizes(userContext);
			}
		}

		#pragma warning restore 1591
		#endregion
	}
}