//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//-----------------------------------------------------------------------------

namespace VahapYigit.Test.Services
{
	using System;
	using System.ServiceModel;
	using System.ServiceModel.Activation;
	using System.Threading.Tasks;
	using System.Transactions;
	using System.Xml;
	
	using VahapYigit.Test.Business;
	using VahapYigit.Test.Contracts;
	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;

	/// <summary>
	/// RoleService Service.
	/// </summary>
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	[AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
	public partial class RoleService : IRoleService
	{
		#region [ IService Implementation ]
		
		bool IService.WakeUp(IUserContext userContext)
		{
			return true;
		}

		async Task<bool> IService.WakeUpAsync(IUserContext userContext)
		{
			return await Task.Factory.StartNew(() => true);
		}

		#endregion

		#region [ IRoleService Implementation ]
		
		/// <summary>
		/// Refreshs the entity instance from the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="appSettings">
		/// Entity to refresh (must be in database).
		/// </param>
		public void Refresh(IUserContext userContext, ref VahapYigit.Test.Models.Role entity)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				db.Refresh(ref entity);
			}
		}
		
		/// <summary>
		/// Gets an entity given its unique ID.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="id">
		/// Unique ID.
		/// </param>
		/// 
		/// <returns>
		/// The entity.
		/// </returns>
		public VahapYigit.Test.Models.Role GetById(IUserContext userContext, long id)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.GetById(id);
			}
		}
		
		/// <summary>
		/// Gets an entity given its unique CodeRef value.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="codeRef">
		/// Unique CodeRef value.
		/// </param>
		/// 
		/// <returns>
		/// The entity.
		/// </returns>
		public VahapYigit.Test.Models.Role GetByCodeRef(VahapYigit.Test.Core.IUserContext userContext, string codeRef)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.GetByCodeRef(codeRef);
			}
		}

		/// <summary>
		/// Gets entities with search options.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional options, filters, orderby, paging, etc.
		/// </param>
		/// 
		/// <returns>
		/// A collection of entities.
		/// </returns>
		public TCollection<VahapYigit.Test.Models.Role> Search(IUserContext userContext, ref SearchOptions options)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.Search(ref options);
			}
		}

		/// <summary>
		/// Gets the number of records that verify the search options.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional search options. If not defined all records are counted.
		/// </param>
		/// 
		/// <returns>
		/// The number of records.
		/// </returns>
		public int Count(IUserContext userContext, SearchOptions options = null)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.Count(options);
			}
		}
		
		/// <summary>
		/// Indicates whether the search returns at least 1 entity.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional search options. If not defined, all records are returned.
		/// </param>
		/// 
		/// <returns>
		/// True if the search returns at least 1 entity; otherwise, false.
		/// </returns>
		public bool HasResult(IUserContext userContext, SearchOptions options = null)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.HasResult(options);
			}
		}
		
		/// <summary>
		/// Saves (or updates) the entity in the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		///
		/// <param name="entity">
		/// Entity to save or update.
		/// </param>
		/// 
		/// <param name="options">
		/// Optional options.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		public int Save(IUserContext userContext, ref VahapYigit.Test.Models.Role entity, SaveOptions options = null)
		{
			using (var et = new ExecutionTracerService(tag: entity.State.ToString()))
			using (var db = new RoleCrud(userContext))
			{
				return db.Save(ref entity, options);
			}
		}
		
		/// <summary>
		/// Deletes the entity from the database.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="entity">
		/// Entity to delete.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		public int Delete(IUserContext userContext,VahapYigit.Test.Models.Role entity)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.Delete(entity);
			}
		}
		
		/// <summary>
		/// Deletes the entity given its unique ID.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="id">
		/// Unique ID.
		/// </param>
		/// 
		/// <returns>
		/// The number of affected rows.
		/// </returns>
		public int Delete(IUserContext userContext, long id)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				return db.Delete(id);
			}
		}

		/// <summary>
		/// Loads the UserRole entities associated to the current instance (entity.UserRoleCollection property).
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="entity">
		/// The target entity.
		/// </param>
		public void LoadUserRoleCollection(IUserContext userContext, ref VahapYigit.Test.Models.Role entity)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				db.LoadUserRoleCollection(ref entity);
			}
		}

		/// <summary>
		/// Loads the UserRole entities associated to the instances (entity.UserRole collection property).
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <param name="entities">
		/// The target entity collection.
		/// </param>
		public void LoadUserRoleCollection(IUserContext userContext, TCollection<VahapYigit.Test.Models.Role> entities)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new RoleCrud(userContext))
			{
				db.LoadUserRoleCollection(entities);
			}
		}

		#endregion
	}
}