-- ------------------------------------------------------------------------------ 
-- <auto-generated> 
-- This code was generated by LayerCake Generator v3.7.1.
-- http://www.layercake-generator.net
-- 
-- Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
-- the code is regenerated. 
-- </auto-generated> 
-- ------------------------------------------------------------------------------

CREATE PROCEDURE AppSettings_Get
(
	@AppSettings_Id BIGINT,

	@CtxUser BIGINT = NULL,
	@CtxCulture VARCHAR(2) = N'EN',
	@CtxWithContextSecurity BIT =  N'True'
)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT	*
	FROM	[AppSettings] WITH(NOLOCK)
	WHERE	[AppSettings].[AppSettings_Id] = @AppSettings_Id;

END
