-- ------------------------------------------------------------------------------ 
-- <auto-generated> 
-- This code was generated by LayerCake Generator v3.7.1.
-- http://www.layercake-generator.net
-- 
-- Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
-- the code is regenerated. 
-- </auto-generated> 
-- ------------------------------------------------------------------------------

CREATE PROCEDURE AppSettings_Save
(
	@AppSettings_Id BIGINT = 0,
	@AppSettings_Key VARCHAR(128),
	@AppSettings_Value VARCHAR(1024),
	@AppSettings_Description VARCHAR(256),

	@CtxUser BIGINT = NULL,
	@CtxCulture VARCHAR(2) = N'EN',
	@CtxWithContextSecurity BIT = N'True'
)
AS
BEGIN

	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	BEGIN TRY
		BEGIN TRANSACTION;

			DECLARE @V_ID BIGINT = @AppSettings_Id;

			IF @AppSettings_Id < 1
			BEGIN
				INSERT INTO [AppSettings]
				(
					 [AppSettings].[AppSettings_Key]
					,[AppSettings].[AppSettings_Value]
					,[AppSettings].[AppSettings_Description]
				)
				VALUES
				(
					 @AppSettings_Key
					,@AppSettings_Value
					,@AppSettings_Description
				);

				SET @V_ID = SCOPE_IDENTITY();

			END
			ELSE
			BEGIN

				DECLARE @V_IS_LOCKED BIT = N'False';

				IF (@V_IS_LOCKED = N'False')
				BEGIN

					IF (EXISTS(	SELECT	TOP 1 1
								FROM	[sys].[tables] WITH(NOLOCK)
								WHERE	[name] = N'AppSettings_LOGS'))
					BEGIN

						DECLARE @V_LOG_QUERY NVARCHAR(MAX) = 
							  N' INSERT INTO [AppSettings_LOGS]'
							+ N' ('
							+ N'  [AppSettings_LOGS].[AppSettings_Id]'
							+ N' ,[AppSettings_LOGS].[AppSettings_Key]'
							+ N' ,[AppSettings_LOGS].[AppSettings_Value]'
							+ N' ,[AppSettings_LOGS].[AppSettings_Description]'
							+ N' )'
							+ N' SELECT'
							+ N'  [AppSettings].[AppSettings_Id]'
							+ N' ,[AppSettings].[AppSettings_Key]'
							+ N' ,[AppSettings].[AppSettings_Value]'
							+ N' ,[AppSettings].[AppSettings_Description]'
							+ N' FROM'
							+ N' [AppSettings] WITH(NOLOCK)'
							+ N' WHERE'
							+ N' [AppSettings].[AppSettings_Id] = @AppSettings_Id;';

						EXECUTE sp_executesql @V_LOG_QUERY, N'@AppSettings_Id BIGINT', @AppSettings_Id;
					END

					UPDATE
						[AppSettings]
					SET
						 [AppSettings].[AppSettings_Key] = @AppSettings_Key
						,[AppSettings].[AppSettings_Value] = @AppSettings_Value
						,[AppSettings].[AppSettings_Description] = @AppSettings_Description
					WHERE
						[AppSettings_Id] = @AppSettings_Id;

				END

			END

		COMMIT TRANSACTION;

		SELECT	*
		FROM	[AppSettings] WITH(NOLOCK)
		WHERE	[AppSettings].[AppSettings_Id] = @V_ID;

		RETURN (@@ROWCOUNT);

	END TRY
	BEGIN CATCH

		IF XACT_STATE() != 0
		BEGIN
			ROLLBACK TRANSACTION;
		END
		DECLARE @V_NOW DATETIME2(3) = GETDATE();
		DECLARE @V_ERROR_MESSAGE VARCHAR(MAX) = ERROR_MESSAGE();
		DECLARE @V_ERROR_SEVERITY INT = ERROR_SEVERITY();
		DECLARE @V_ERROR_STATE INT = ERROR_STATE();

		-- RAISE() must be called before EXEC [ProcessErrorLog_Save] in order to get the error
		-- on the first result in the SqlDataReader (Save stored procedures return 1 row).

		RAISERROR(@V_ERROR_MESSAGE, @V_ERROR_SEVERITY, @V_ERROR_STATE);

		EXEC [ProcessErrorLog_Save]
			 @ProcessErrorLog_Date = @V_NOW,
			 @ProcessErrorLog_ProcedureName = N'AppSettings_Save',
			 @ProcessErrorLog_ErrorMessage = @V_ERROR_MESSAGE,
			 @ProcessErrorLog_ErrorSeverity = @V_ERROR_SEVERITY,
			 @ProcessErrorLog_ErrorState = @V_ERROR_STATE,
			 @ProcessErrorLog_Data = NULL,
			 @CtxUser = @CtxUser,
			 @CtxCulture = @CtxCulture,
			 @CtxWithContextSecurity = @CtxWithContextSecurity;

		RETURN (@@ROWCOUNT);

	END CATCH
END