-- ------------------------------------------------------------------------------ 
-- <auto-generated> 
-- This code was generated by LayerCake Generator v3.7.1.
-- http://www.layercake-generator.net
-- 
-- Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
-- the code is regenerated. 
-- </auto-generated> 
-- ------------------------------------------------------------------------------

CREATE PROCEDURE User_Get
(
	@User_Id BIGINT,
	@User_Email VARCHAR(256),

	@CtxUser BIGINT = NULL,
	@CtxCulture VARCHAR(2) = N'EN',
	@CtxWithContextSecurity BIT =  N'True'
)
AS
BEGIN
	SET NOCOUNT ON;

	IF @User_Email IS NOT NULL
	BEGIN

		SELECT	*
		FROM	[User] WITH(NOLOCK)
		WHERE	UPPER([User].[User_Email]) = UPPER(@User_Email);

	END
	ELSE
	BEGIN

		SELECT	*
		FROM	[User] WITH(NOLOCK)
		WHERE	[User].[User_Id] = @User_Id;

	END
END
GO
