-- ------------------------------------------------------------------------------ 
-- <auto-generated> 
-- This code was generated by LayerCake Generator v3.7.1.
-- http://www.layercake-generator.net
-- 
-- Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
-- the code is regenerated. 
-- </auto-generated> 
-- ------------------------------------------------------------------------------

CREATE PROCEDURE UserRole_Get
(
	@UserRole_Id BIGINT,

	@CtxUser BIGINT = NULL,
	@CtxCulture VARCHAR(2) = N'EN',
	@CtxWithContextSecurity BIT =  N'True'
)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT	*
	FROM	[UserRole] WITH(NOLOCK)
	WHERE	[UserRole].[UserRole_Id] = @UserRole_Id;

END
