//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace LayerCake.Generator.Commons
{
	using System.Xml.Serialization;


	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ModelDescriptorSchema
	{

		private ModelDescriptorSchemaTable[] tablesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Table", IsNullable = false)]
		public ModelDescriptorSchemaTable[] Tables
		{
			get
			{
				return this.tablesField;
			}
			set
			{
				this.tablesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTable
	{

		private string nameField;

		private bool hasIdUserColumnField;

		private bool hasCodeRefColumnField;

		private bool isOwnershipField;

		private ModelDescriptorSchemaTableColumn[] columnsField;

		private ModelDescriptorSchemaTableCodeRef[] codeRefsField;

		private ModelDescriptorSchemaTableUnique[] constraintsField;

		private ModelDescriptorSchemaTableZeroToOneRelation[] zeroToOneRelationsField;

		private ModelDescriptorSchemaTableZeroToManyRelation[] zeroToManyRelationsField;

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public bool HasIdUserColumn
		{
			get
			{
				return this.hasIdUserColumnField;
			}
			set
			{
				this.hasIdUserColumnField = value;
			}
		}

		/// <remarks/>
		public bool HasCodeRefColumn
		{
			get
			{
				return this.hasCodeRefColumnField;
			}
			set
			{
				this.hasCodeRefColumnField = value;
			}
		}

		/// <remarks/>
		public bool IsOwnership
		{
			get
			{
				return this.isOwnershipField;
			}
			set
			{
				this.isOwnershipField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable = false)]
		public ModelDescriptorSchemaTableColumn[] Columns
		{
			get
			{
				return this.columnsField;
			}
			set
			{
				this.columnsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("CodeRef", IsNullable = false)]
		public ModelDescriptorSchemaTableCodeRef[] CodeRefs
		{
			get
			{
				return this.codeRefsField;
			}
			set
			{
				this.codeRefsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("ZeroToOneRelation", IsNullable = false)]
		public ModelDescriptorSchemaTableZeroToOneRelation[] ZeroToOneRelations
		{
			get
			{
				return this.zeroToOneRelationsField;
			}
			set
			{
				this.zeroToOneRelationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("ZeroToManyRelation", IsNullable = false)]
		public ModelDescriptorSchemaTableZeroToManyRelation[] ZeroToManyRelations
		{
			get
			{
				return this.zeroToManyRelationsField;
			}
			set
			{
				this.zeroToManyRelationsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Unique", IsNullable = false)]
		public ModelDescriptorSchemaTableUnique[] Constraints
		{
			get
			{
				return this.constraintsField;
			}
			set
			{
				this.constraintsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableColumn
	{

		private string nameField;

		private bool isNullableField;

		private string sqlTypeNameField;

		private string sqlTypeNameExField;

		private int? maximumLengthField;

		private int? numericPrecisionField;

		private int? numericScaleField;

		private string cSharpTypeNameField;

		private string cSharpPropertyNameField;

		private bool cSharpIsTypeNullableField;

		private bool isForeignKeyField;

		private bool isIdColumnField;

		private bool isLanguageColumnField;

		private ModelDescriptorSchemaTableColumnLanguageColumn[] languageColumnsField;

		private bool isOwnershipColumnField;

		private ModelDescriptorSchemaTableColumnForeignKey foreignKeyField;

		private string descriptionField;

		private string defaultValueField;

		private ModelDescriptorSchemaTableColumnDefaultValue[] defaultValuesField;

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public bool IsNullable
		{
			get
			{
				return this.isNullableField;
			}
			set
			{
				this.isNullableField = value;
			}
		}

		/// <remarks/>
		public string SqlTypeName
		{
			get
			{
				return this.sqlTypeNameField;
			}
			set
			{
				this.sqlTypeNameField = value;
			}
		}

		/// <remarks/>
		public string SqlTypeNameEx
		{
			get
			{
				return this.sqlTypeNameExField;
			}
			set
			{
				this.sqlTypeNameExField = value;
			}
		}

		/// <remarks/>
		public int? MaximumLength
		{
			get
			{
				return this.maximumLengthField;
			}
			set
			{
				this.maximumLengthField = value;
			}
		}

		/// <remarks/>
		public int? NumericPrecision
		{
			get
			{
				return this.numericPrecisionField;
			}
			set
			{
				this.numericPrecisionField = value;
			}
		}

		/// <remarks/>
		public int? NumericScale
		{
			get
			{
				return this.numericScaleField;
			}
			set
			{
				this.numericScaleField = value;
			}
		}

		/// <remarks/>
		public string CSharpTypeName
		{
			get
			{
				return this.cSharpTypeNameField;
			}
			set
			{
				this.cSharpTypeNameField = value;
			}
		}

		/// <remarks/>
		public string CSharpPropertyName
		{
			get
			{
				return this.cSharpPropertyNameField;
			}
			set
			{
				this.cSharpPropertyNameField = value;
			}
		}

		/// <remarks/>
		public bool CSharpIsTypeNullable
		{
			get
			{
				return this.cSharpIsTypeNullableField;
			}
			set
			{
				this.cSharpIsTypeNullableField = value;
			}
		}

		/// <remarks/>
		public bool IsForeignKey
		{
			get
			{
				return this.isForeignKeyField;
			}
			set
			{
				this.isForeignKeyField = value;
			}
		}

		/// <remarks/>
		public bool IsIdColumn
		{
			get
			{
				return this.isIdColumnField;
			}
			set
			{
				this.isIdColumnField = value;
			}
		}

		/// <remarks/>
		public bool IsLanguageColumn
		{
			get
			{
				return this.isLanguageColumnField;
			}
			set
			{
				this.isLanguageColumnField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("LanguageColumn", IsNullable = false)]
		public ModelDescriptorSchemaTableColumnLanguageColumn[] LanguageColumns
		{
			get
			{
				return this.languageColumnsField;
			}
			set
			{
				this.languageColumnsField = value;
			}
		}

		/// <remarks/>
		public bool IsOwnershipColumn
		{
			get
			{
				return this.isOwnershipColumnField;
			}
			set
			{
				this.isOwnershipColumnField = value;
			}
		}

		/// <remarks/>
		public ModelDescriptorSchemaTableColumnForeignKey ForeignKey
		{
			get
			{
				return this.foreignKeyField;
			}
			set
			{
				this.foreignKeyField = value;
			}
		}

		/// <remarks/>
		public string Description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		public string DefaultValue
		{
			get
			{
				return this.defaultValueField;
			}
			set
			{
				this.defaultValueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("DefaultValue", IsNullable = false)]
		public ModelDescriptorSchemaTableColumnDefaultValue[] DefaultValues
		{
			get
			{
				return this.defaultValuesField;
			}
			set
			{
				this.defaultValuesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableColumnLanguageColumn
	{

		private string nameField;

		private string cultureField;

		private string cSharpPropertyNameField;

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public string Culture
		{
			get
			{
				return this.cultureField;
			}
			set
			{
				this.cultureField = value;
			}
		}

		/// <remarks/>
		public string CSharpPropertyName
		{
			get
			{
				return this.cSharpPropertyNameField;
			}
			set
			{
				this.cSharpPropertyNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableColumnForeignKey
	{

		private string tableNameField;

		private string columnNameField;

		private string cSharpPropertyNameField;

		/// <remarks/>
		public string TableName
		{
			get
			{
				return this.tableNameField;
			}
			set
			{
				this.tableNameField = value;
			}
		}

		/// <remarks/>
		public string ColumnName
		{
			get
			{
				return this.columnNameField;
			}
			set
			{
				this.columnNameField = value;
			}
		}

		/// <remarks/>
		public string CSharpPropertyName
		{
			get
			{
				return this.cSharpPropertyNameField;
			}
			set
			{
				this.cSharpPropertyNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableColumnDefaultValue
	{

		private string cultureField;

		private string valueField;

		/// <remarks/>
		public string Culture
		{
			get
			{
				return this.cultureField;
			}
			set
			{
				this.cultureField = value;
			}
		}

		/// <remarks/>
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableCodeRef
	{

		private long idField;

		private string valueField;

		/// <remarks/>
		public long Id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableUnique
	{

		private ModelDescriptorSchemaTableUniqueColumn[] columnsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable = false)]
		public ModelDescriptorSchemaTableUniqueColumn[] Columns
		{
			get
			{
				return this.columnsField;
			}
			set
			{
				this.columnsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableUniqueColumn
	{

		private string nameField;

		private string nameWithoutTableNameField;

		private string cultureField;

		private string nameWithoutCultureField;

		private string nameWithoutTableNameWithoutCultureField;

		/// <remarks/>
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		public string NameWithoutTableName
		{
			get
			{
				return this.nameWithoutTableNameField;
			}
			set
			{
				this.nameWithoutTableNameField = value;
			}
		}

		/// <remarks/>
		public string Culture
		{
			get
			{
				return this.cultureField;
			}
			set
			{
				this.cultureField = value;
			}
		}

		/// <remarks/>
		public string NameWithoutCulture
		{
			get
			{
				return this.nameWithoutCultureField;
			}
			set
			{
				this.nameWithoutCultureField = value;
			}
		}

		/// <remarks/>
		public string NameWithoutTableNameWithoutCulture
		{
			get
			{
				return this.nameWithoutTableNameWithoutCultureField;
			}
			set
			{
				this.nameWithoutTableNameWithoutCultureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableZeroToOneRelation
	{

		private bool isLoopField;

		private string tableNameField;

		private string columnNameField;

		private string referencedTableNameField;

		private string referencedColumnNameField;

		private string cSharpPropertyNameField;

		/// <remarks/>
		public bool IsLoop
		{
			get
			{
				return this.isLoopField;
			}
			set
			{
				this.isLoopField = value;
			}
		}

		/// <remarks/>
		public string TableName
		{
			get
			{
				return this.tableNameField;
			}
			set
			{
				this.tableNameField = value;
			}
		}

		/// <remarks/>
		public string ColumnName
		{
			get
			{
				return this.columnNameField;
			}
			set
			{
				this.columnNameField = value;
			}
		}

		/// <remarks/>
		public string ReferencedTableName
		{
			get
			{
				return this.referencedTableNameField;
			}
			set
			{
				this.referencedTableNameField = value;
			}
		}

		/// <remarks/>
		public string ReferencedColumnName
		{
			get
			{
				return this.referencedColumnNameField;
			}
			set
			{
				this.referencedColumnNameField = value;
			}
		}

		/// <remarks/>
		public string CSharpPropertyName
		{
			get
			{
				return this.cSharpPropertyNameField;
			}
			set
			{
				this.cSharpPropertyNameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ModelDescriptorSchemaTableZeroToManyRelation
	{
		private bool isLoopField;

		private string tableNameField;

		private string columnNameField;

		private string referencedTableNameField;

		private string referencedColumnNameField;

		private string cSharpPropertyNameField;

		/// <remarks/>
		public bool IsLoop
		{
			get
			{
				return this.isLoopField;
			}
			set
			{
				this.isLoopField = value;
			}
		}

		/// <remarks/>
		public string TableName
		{
			get
			{
				return this.tableNameField;
			}
			set
			{
				this.tableNameField = value;
			}
		}

		/// <remarks/>
		public string ColumnName
		{
			get
			{
				return this.columnNameField;
			}
			set
			{
				this.columnNameField = value;
			}
		}

		/// <remarks/>
		public string ReferencedTableName
		{
			get
			{
				return this.referencedTableNameField;
			}
			set
			{
				this.referencedTableNameField = value;
			}
		}

		/// <remarks/>
		public string ReferencedColumnName
		{
			get
			{
				return this.referencedColumnNameField;
			}
			set
			{
				this.referencedColumnNameField = value;
			}
		}

		/// <remarks/>
		public string CSharpPropertyName
		{
			get
			{
				return this.cSharpPropertyNameField;
			}
			set
			{
				this.cSharpPropertyNameField = value;
			}
		}
	}
}
