//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Business
{
	using System;
	using System.Collections.Generic;

	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;
	using VahapYigit.Test.Models;

	/// <summary>
	/// This class contains ExecutionTrace business methods.
	/// </summary>
	[BusinessClass]
	public class ExecutionTraceBusiness : BusinessBase
	{
		#region [ Custom public methods ]

		[BusinessMethod]
		public void Trace(IUserContext userContext, ExecutionTraceModel[] traces)
		{
			if (!traces.IsNullOrEmpty())
			{
				using (var db = new ExecutionTraceCrud(userContext))
				{
					db.Trace(traces);
				}
			}
		}

		#endregion
	}
}