//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Business
{
	using System;
	using System.Collections.Generic;
	using System.ServiceModel;

	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;

	/// <summary>
	/// This class contains ProcessLog business methods.
	/// </summary>
	[BusinessClass]
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession)]
	public class ProcessLogBusiness : BusinessBase
	{
		// This class contains business methods.
		// All the methods must have the IUserContext userContext parameter.
		// 
		// DO NOT ADD REFERENCE ON VahapYigit.Test.Service THERE!
		// ONLY USE BUSINESS AND CRUD LAYERS!

		#region [ Custom public methods ]

		/// <summary>
		/// Remove all records from the DB table.
		/// </summary>
		/// 
		/// <param name="userContext">
		/// User context.
		/// </param>
		/// 
		/// <returns>
		/// The number of records deleted.
		/// </returns>
		[BusinessMethod]
		public int Purge(IUserContext userContext)
		{
			using (var et = new ExecutionTracerService())
			using (var db = new ProcessLogCrud(userContext))
			{
				return db.Purge();
			}
		}

		#endregion

		#region [ Custom private methods ]



		#endregion
	}
}