//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Business
{
	using System;
	using System.Collections.Generic;
	using System.ServiceModel;
	using System.Transactions;

	using VahapYigit.Test.Business;
	using VahapYigit.Test.Core;
	using VahapYigit.Test.Crud;
	using VahapYigit.Test.Models;

	/// <summary>
	/// This class contains User business methods.
	/// </summary>
	[BusinessClass]
	public class UserBusiness : BusinessBase
	{
		// This class contains business methods.
		// All the methods should have the IUserContext userContext parameter.
		// 
		// DO NOT ADD REFERENCE TO VahapYigit.Test.Services.dll!
		// ONLY USE BUSINESS AND CRUD CLASSES!

		#region [ Custom public methods ]



		#endregion

		#region [ Custom private methods ]



		#endregion
	}
}