//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Crud
{
	using System;
	using System.Collections.Generic;
	using System.Data;

	using VahapYigit.Test.Models;
	using VahapYigit.Test.Core;

	public partial class ExecutionTraceCrud
	{
		public void Trace(params ExecutionTraceModel[] traces)
		{
			if (!traces.IsNullOrEmpty())
			{
				var parameters = new Dictionary<string, object>();

				parameters.Add("@TvpExecutionTrace", CreateTvpExecutionTrace(traces));

				base.ExecuteNonQuery("ExecutionTrace_Custom_Trace", parameters);
			}
		}

		#region [ Private Methods ]

		private static DataTable CreateTvpExecutionTrace(ExecutionTraceModel[] traces)
		{
			DataTable data = new DataTable();

			// This columns maps the TvpExecutionTrace ones.

			data.Columns.Add("Module", typeof(string));
			data.Columns.Add("Namespace", typeof(string));
			data.Columns.Add("MethodName", typeof(string));
			data.Columns.Add("Tag", typeof(string));
			data.Columns.Add("Duration", typeof(int));
			data.Columns.Add("LastCall", typeof(DateTime));

			foreach (var trace in traces)
			{
				DataRow row = data.NewRow();

				row["Module"] = trace.Module;
				row["Namespace"] = trace.ClassName;
				row["MethodName"] = trace.MethodName;
				row["Tag"] = trace.Tag;
				row["Duration"] = trace.Duration;
				row["LastCall"] = trace.LastCall;

				data.Rows.Add(row);
			}

			return data;
		}

		#endregion
	}
}