//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file WILL NOT BE LOST if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Crud
{
	using System;

	using VahapYigit.Test.Core;

	public partial class ProcessLogCrud
	{
		/// <summary>
		/// Remove all records from the DB table.
		/// </summary>
		/// <returns></returns>
		public int Purge()
		{
			using (var et = new ExecutionTracerService())
			{
				return base.ExecuteScalar<int>("ProcessLog_Custom_Purge", null);
			}
		}
	}
}