//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Core
{
	using System;
	using System.ComponentModel;
	using System.Runtime.Serialization;
	using System.Xml.Serialization;

	[Serializable]
	[DataContract]
	[DefaultValue(TranslationEnum.None)]
	public enum TranslationEnum
	{
		[XmlEnum()]
		[EnumMember()]
		None,

		[XmlEnum()]
		[EnumMember()]
		CrudAppSettingsKeyUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudRoleCodeRefUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudRoleNameUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudTranslationKeyUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudUserEmailUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudUserRoleIdUser_IdRoleUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CrudUserUsernameUniqueConstraint,

		[XmlEnum()]
		[EnumMember()]
		CustomExceptionSmtpBadRecipient,

		[XmlEnum()]
		[EnumMember()]
		ModelAppSettingsDescriptionBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelAppSettingsKeyBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelAppSettingsKeyIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelAppSettingsValueBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelAppSettingsValueIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceClassNameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceClassNameIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceCounterBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceCounterIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceLastCallBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceLastCallIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMaxDurationBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMaxDurationIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMethodNameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMethodNameIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMinDurationBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceMinDurationIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceModuleBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceModuleIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceTagBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceTotalDurationBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelExecutionTraceTotalDurationIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogDataBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogDateBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogDateIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogErrorMessageBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogErrorSeverityBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogErrorStateBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogProcedureNameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessErrorLogProcedureNameIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessLogDataBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessLogDateBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessLogDateIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessLogProcedureNameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelProcessLogProcedureNameIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelRoleCodeRefBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelRoleCodeRefIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelRoleNameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelRoleNameIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelTranslationKeyBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelTranslationKeyIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelTranslationValueBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelTranslationValueIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserCultureBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserCultureIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserEmailBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserEmailIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserLastConnectionDateBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordQuestionBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordQuestionIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordResponseBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserPasswordResponseIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRegistrationDateBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRegistrationDateIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRoleIdRoleBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRoleIdRoleIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRoleIdUserBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserRoleIdUserIsRequired,

		[XmlEnum()]
		[EnumMember()]
		ModelUserUsernameBadValueOrFormat,

		[XmlEnum()]
		[EnumMember()]
		ModelUserUsernameIsRequired,
	}
}