//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;

	using VahapYigit.Test.Core;

	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public partial interface IAppSettings : IEntity
	{
		#region [ Properties ]

		/// <summary>
		/// Gets or sets the Key value (MANDATORY). 
		/// </summary>
		string Key { get; set; }

		/// <summary>
		/// Gets or sets the Value value (MANDATORY). 
		/// </summary>
		string Value { get; set; }

		/// <summary>
		/// Gets or sets the Description value (OPTIONAL). 
		/// </summary>
		string Description { get; set; }


		#endregion
	}
	
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public static partial class IAppSettingsExtensions
	{
		public static void MapFrom(this IAppSettings target, IAppSettings source)
		{
			if (source != null)
			{
				if (target != null)
				{
					target.Key = source.Key;
					target.Value = source.Value;
					target.Description = source.Description;
				}
			}
		}

		public static void MapTo(this IAppSettings source, IAppSettings target)
		{
			target.MapFrom(source);
		}
	}
}