//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;

	using VahapYigit.Test.Core;

	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public partial interface IProcessLog : IEntity
	{
		#region [ Properties ]

		/// <summary>
		/// Gets or sets the Date value (MANDATORY). 
		/// </summary>
		DateTime Date { get; set; }

		/// <summary>
		/// Gets or sets the ProcedureName value (MANDATORY). 
		/// </summary>
		string ProcedureName { get; set; }

		/// <summary>
		/// Gets or sets the Data value (OPTIONAL). 
		/// </summary>
		string Data { get; set; }


		#endregion
	}
	
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public static partial class IProcessLogExtensions
	{
		public static void MapFrom(this IProcessLog target, IProcessLog source)
		{
			if (source != null)
			{
				if (target != null)
				{
					target.Date = source.Date;
					target.ProcedureName = source.ProcedureName;
					target.Data = source.Data;
				}
			}
		}

		public static void MapTo(this IProcessLog source, IProcessLog target)
		{
			target.MapFrom(source);
		}
	}
}