//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;

	using VahapYigit.Test.Core;

	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public partial interface ITranslation : IEntity
	{
		#region [ Properties ]

		/// <summary>
		/// Gets or sets the Key value (MANDATORY). 
		/// </summary>
		string Key { get; set; }

		/// <summary>
		/// Gets or sets the Value value (MANDATORY). 
		/// </summary>
		VahapYigit.Test.Core.LanguageCollection Value { get; set; }


		#endregion
	}
	
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public static partial class ITranslationExtensions
	{
		public static void MapFrom(this ITranslation target, ITranslation source)
		{
			if (source != null)
			{
				if (target != null)
				{
					target.Key = source.Key;
					target.Value = new LanguageCollection(source.Value);
				}
			}
		}

		public static void MapTo(this ITranslation source, ITranslation target)
		{
			target.MapFrom(source);
		}
	}
}