//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;

	using VahapYigit.Test.Core;

	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public partial interface IUserRole : IEntity
	{
		#region [ Properties ]

		/// <summary>
		/// Gets or sets the IdUser value (MANDATORY). 
		/// </summary>
		long IdUser { get; set; }

		/// <summary>
		/// Gets or sets the IdRole value (MANDATORY). 
		/// </summary>
		long IdRole { get; set; }


		#endregion

		#region [ References ]

		/// <summary>
		/// Referenced User entity by this entity.
		/// </summary>
		User User { get; set; }

		/// <summary>
		/// Referenced Role entity by this entity.
		/// </summary>
		Role Role { get; set; }

		#endregion
	}
	
	[System.CodeDom.Compiler.GeneratedCode("LayerCake Generator", "3.7.1")]
	public static partial class IUserRoleExtensions
	{
		public static void MapFrom(this IUserRole target, IUserRole source)
		{
			if (source != null)
			{
				if (target != null)
				{
					target.IdUser = source.IdUser;
					target.IdRole = source.IdRole;
				}
			}
		}

		public static void MapTo(this IUserRole source, IUserRole target)
		{
			target.MapFrom(source);
		}
	}
}