//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by LayerCake Generator v3.7.1.
// http://www.layercake-generator.net
// 
// Changes to this file may cause incorrect behavior AND WILL BE LOST IF 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace VahapYigit.Test.Models
{
	using System;
	using System.Runtime.Serialization;

	[KnownType(typeof(VahapYigit.Test.Models.AppSettings))]
	[KnownType(typeof(VahapYigit.Test.Models.ExecutionTrace))]
	[KnownType(typeof(VahapYigit.Test.Models.ProcessErrorLog))]
	[KnownType(typeof(VahapYigit.Test.Models.ProcessLog))]
	[KnownType(typeof(VahapYigit.Test.Models.Role))]
	[KnownType(typeof(VahapYigit.Test.Models.Translation))]
	[KnownType(typeof(VahapYigit.Test.Models.User))]
	[KnownType(typeof(VahapYigit.Test.Models.UserRole))]
	public abstract partial class EntityBase
	{
	}
}